### PR TITLE
Backend Plugin: Allow hashed passwords in configuration

### PR DESCRIPTION
**Pull request by i-am-offline**
I really like your new backend plugin .. but I don't like plaintext passwords in config files.

This change introduces a new configuration parameter "md5password". It can be used
instead of parameter "passwort" and should contain the password as md5 hash. So no
plaintext password is visible in the configuration file.

Documentation has been adapted accordingly

It may be worth discussing whether the "password" parameter should be declared as obsolete and can be removed at some later release.

There might be a merge conflict between this PR and my other PR #100. I will update this PR if #100 has been merged (or vice-versa).

### CODE REVIEW

**Comment by smaiLee** [comment]
What do you think about the following idea:
One can add the parameter _password_ in conf. On startup of the plugin the parameter _md5password_ is automatically calculated and added to conf file and the parameter _password_ get removed.
But actually i'm not sure if the plugin can edit the conf file.

In addition MD5 actually is not real secure. As [hashlib](https://docs.python.org/3/library/hashlib.html) has no particularly suitable password hashing algoritm which is always present, I would use at least SHA-256 or SHA-512 for this purpose.

**Comment by ohinckel** [comment]
Let the plugin change the configuration is not a good idea. I always do not like applications changing configuration files and make them looking differently as it was before (e.g. removing comments, empty lines or reformat the file completely).

But spporting other hashes than MD5 would be a good advice. Maybe we can go further with this enhancement: instead of naming the setting md5password we could specify the hash type in the value (e.g. "{CRYPT}abcdef" for MD5, "{SHA-1}abcde", .. or "abcde" for plain-text). The plugin then just read the setting and us a common password function (e.g. provided in tools.py or utils.py) to verify a password with the configuration value). This function will check the hash type and check the password accordingly.

This could also be something we could support when all te plugin will have a configuration section in the code specifying which parameters are allowed and which type they are (numer, string, bool, pasword, ...) - the idea mentioned in some other isues/PR which I can not find currently and implemented with #27.

**Comment by smaiLee** [comment]
I see the point of not changing configuration files by application.
But IMHO its annoying if you have to calculate a hashed password by yourself and add it to configuration file.
The structure and look of the file should not be changed by this - only the password parameter would by replaced by encrypted password parameter.
I also support your suggestion with hashing algorithm in the value. In this case nothing than the value of password parameter would be changed by automatic encryption.
If we think further we could allow e.g. {plain-text} as algorithm prefix. If this is specified, no automatic encryption would take place. So users who don't want there password to be encrypted can specify this.

**Comment by psilo909** [comment]
typically, i would say that sh.py  is not publicly available in the internet. the instance is protected by a vpn. so the password is only for the local area network of the user. do you see this really as critical as webapps hosted public?!? 

for me at least the possibility to use any password was important, so that users in my guest wifi cant access the backend. theoretically, you can also access the cli without a password and change everything..

**Comment by i-am-offline** [comment]
I agree that sh.py must not be publicly available. This is why the password in the configuration file does not need to be heavily encrypted. However, in my opinion it should be at least "obfuscated".

The main reason why I made this change is, that I want to prevent people (actually my children or some friends to whom I show how great sh.py is ;-)) ) to look over my shoulder and "accidentally" read the password from the screen while I'm editing the config file. 

The reason why I decided for hashlib was, that it does (as far as I know) not add an additional dependency. I'm open to using a different algorithm such as the proposed sha-256 or sha-512. 

I dislike the idea, that the plugin should change the configuration file, too. No program should be of the opinion that it knows better what the user wants to do than the user himself (Hello Microsoft ...) Either the user enters a plaintext password and then stays plaintext or he enters a md5password and it's md5.

**Comment by smaiLee** [comment]
Actually I'm myself of two minds about this.
On one hand you're right, programs should do what user want them to. On the other hand should security be as easy to handle as possible ("Security By Default").
Let the user encrypt his password by a third party software is not straightforward for most users.

What about following suggestion:
We implement the possibility to encrypt the password in backend GUI itself.
So there is no automatism but there's a simple way to do it.
Either this function could encrypt the password in config file itself (if at all possible) or at least prints out the encrypted password so the user can edit the config himself.

**Comment by ohinckel** [comment]
Generating hashes by the backend GUI is a good thing: people do not mess around with any complex stuff generating the correct hashes, they just can do it by one click.

Protecting the CLI interface is also a good thing we should implement. And protecting the socket may be also an important thing (maybe by a token instead of a password). But in both cases one need to have access to the network to be able to change things (via CLI or socket). The backend GUI can be just opened by the device showing the visu - so this is easier and should be protected by a password!

One more note on hashinh passwords: I really don't like plain text passwords anywhere. I always want to check-in all my stuff (code and configuration) into a repository where others may have acess to it. Using plain text paswords there is really bad and makes it impossible to put the configuration into a VCS.

**Comment by i-am-offline** [comment]
So habe nun meine aktuellsten Commits gepusht:

- Das Eingabefeld für den zu hashenden Wert im Backend ist nun ein Password Feld. Man kann es aber über eine Checkbox in ein Textfeld umschalten
- Anstatt eigener Funktionen werden nun die Funktionen in Utils.py zum Generieren und Prüfen des Hashs verwendet

**Comment by i-am-offline** [comment]
Just merged the current develop branch so that this PR becomes mergeable again, but now I gent an error from Travis CI. However, I can not find the mentioned line 

    File "/home/travis/build/smarthomeNG/smarthome/.tox/py32/lib/python3.2/site-packages/_pytest/python.py", line 1410
    plus_minus = u'{0} \u00b1 {1}'.format(self.expected, vetted_tolerance)

anywhere in smarthomeNG? What do I need to do?

**Pull request merged**
