### PR TITLE
imported math-module to support eval expressions

### PR DESCRIPTION
**Pull request by hotzen**
hello,
imported the math module to support eval expressions like the following:

[[[[stellantrieb]]]]
type = num
eval = math.floor( value / 255 * 100 )
knx_dpt = 5
knx_listen = 3/2/5
knx_init = 3/2/5

### CODE REVIEW

**Comment by ohinckel** [comment]
I think this is a good thing. Maybe other modules could also be imported to support more features in `eval` expressions. Further we should document which modules are availabe inthe Wiki.

Another idea would be to move this into a configuration setting of `smarthome.conf` and configure which modules will be imported automatically and availabe in `eval` expressions then. This would at least be more flexible (especially when someone want to use a 3rd vendor module in these expressions).

**Comment by psilo909** [comment]
@ohinckel i am not sure if a "noob" user would understand what to configure there. for my opinion we could extend the feature set and document it as shown in the PR

**Comment by ohinckel** [comment]
Sure, we could use a default set of modules to import and write it down into the documentation. But we could also provide a configuration setting (maybe only for the pros of us) to cknfigure additional modules. I think this could be a combined solution with #120.

**Comment by wvhn** [comment]
This would simplify math expressions of course. Just for reference: a workaround can be found in [this](https://knx-user-forum.de/forum/supportforen/smarthome-py/1015498-eval_update_item-update-auf-fremde-items?p=1016176#post1016176) post.

**Pull request merged**
