### PR TITLE
changed detection of path to os.path.normpath 

### PR DESCRIPTION
**Pull request by smaugs**
instead of os.path.realpath.

os.path.realpath eliminates any symbolic links - and therefore you can't work with symbolic links for redirecting log files.

I am using the following file structure to eliminate the need to store my items, logs & so on in the application directory. The application directory (as checked out from github) should be replaceable - without even thinking about to backup this or that. config should be in completely seperate directories.

lrwxrwxrwx 1 root      root        18 Feb 18 13:19 bin -> ../smarthomeNG/bin
lrwxrwxrwx 1 root      root        18 Feb 18 13:20 dev -> ../smarthomeNG/dev
lrwxrwxrwx 1 root      root        18 Feb 18 13:20 doc -> ../smarthomeNG/doc
lrwxrwxrwx 1 root      root        22 Feb 18 13:19 etc -> /var/lib/smarthome/etc
lrwxrwxrwx 1 root      root        24 Feb 18 13:19 items -> /var/lib/smarthome/items
lrwxrwxrwx 1 root      root        18 Feb 18 13:19 lib -> ../smarthomeNG/lib
lrwxrwxrwx 1 root      root        25 Feb 18 13:19 logics -> /var/lib/smarthome/logics
lrwxrwxrwx 1 root      root        22 Feb 18 13:40 plugins -> ../smarthomeNG_plugins
lrwxrwxrwx 1 root      root        20 Feb 18 13:20 tests -> ../smarthomeNG/tests
lrwxrwxrwx 1 root      root        20 Feb 18 13:20 tools -> ../smarthomeNG/tools

drwxr-xr-x 2 smarthome smarthome 4096 Feb 18 13:25 var
lrwxrwxrwx 1 root      root        20 Feb 18 13:22 cache -> /var/cache/smarthome
lrwxrwxrwx 1 root      root        21 Feb 18 13:23 db -> /var/lib/smarthome/db
lrwxrwxrwx 1 root      root        18 Feb 18 13:23 log -> /var/log/smarthome
lrwxrwxrwx 1 root      root        22 Feb 18 13:25 rrd -> /var/lib/smarthome/rrd
lrwxrwxrwx 1 root      root        18 Feb 18 13:24 run -> /var/run/smarthome

my start-script starts /opt/smarthome/bin/smarthome.py. when using os.path.realpath it switches to /opt/smarthomeNG - that's not what I want - and probably others too. With normpath everything works like a charm - the smarthomeNG directory is absolutely replaceable.

### CODE REVIEW

**Comment by ohinckel** [comment]
I just tried to use `normpath` instead of `realpath` and it did not work. I'm not using symlinks at all. So did you try it without having symlinks?

**Comment by smaugs** [comment]
to be honest - no. Let me have a look at it and come back to you.

PS: How do you split the smarthomeNG code and its configuration? In the past (I'm using smarthome.py/smarthomeNG for a pretty long time now) I had different problems with upgrading/merging/testing because of "that".

Splitting Config and Code would also be very helpful in the smartvisu project where I ran in the same problems.

If you have any other suggestions for reaching that goal - I am open for suggestions :)

**Comment by ohinckel** [comment]
For me I changed the implementation for both smaerthome and smartvisu.

In smarthome I extend the config setup to be able to specify additional pathes (or config sources, e.g. database) to read the configuation from (for smarthome, plugins, logics and items). So I'm flexible specifying where to search for configurations (I could provide a PR for this, but I don't know what the others think about such a feature).

For smartvisu I extend the config setup to read other config files based on the hostname serving the visu. This made me also flexible to be abe to use one visu installation with different configuration files (using different hostnames for the visu).

Anyway, had you some time to test your changes further?

**Comment by bmxp** [comment]
> to be honest - no. Let me have a look at it and come back to you. 
How is the forthcoming of your look at it? I would like to close the PR unless you have found a working solution in the meantime as we prepare release 1.3 now.

I would suggest to discuss SmartVISU related issues at https://github.com/Martin-Gleiss/smartvisu/issues.

**Comment by bmxp** [comment]
As there are no proceedings here, I will close this PR now. Feel free to come up with a new solution later on.

**Pull request closed without merging**
