### PR TITLE
Webinterface Icon handling

### PR DESCRIPTION
**Pull request by stoepf**

### CODE REVIEW

**Comment by msinn** [comment]
This PR would change the icon in the browser tabs from the SH icon only if a plugin_logo.png file exists for the plugin.
For plugins with other logo images (e.g. .svg) the icon shown would be the SH icon (as ist was). Was that what you wanted to achieve?

On the other hand, you would not see at first glance, that the browser tab belongs to SmartHomeNG.  The actual (develop) version of SmartHomeNG would show the SH icon followed by the text "xxx plugin". Isn't that enough to identify the tab you want to select?

**Comment by stoepf** [comment]
Yes, that was intended. But perhaps it's better not to change the favicon and only use the favicon as apple-touch-icon if no explicit apple-touch-icon is provided.

**Comment by msinn** [comment]
I think, leaving the favicon as the SmartHomeNG icon ist the best, since the browser tabs "belong" to SmartHomeNG.

I like the idea having a home screen icon showing the plugin logo in the iPone or iPad, since the Text isn't shown in every situation.

Could you revert the favicon to the original. I will merge the PR afterwards, so it is included in the next release (probably end of next week).

**Comment by stoepf** [comment]
Favicon change reverted.

**Pull request merged**
