### PR TITLE
Fix conf_to_yaml_converter.py from CRLF to LF

### PR DESCRIPTION
**Pull request by encbladexp**
CRLF as line termination causes Issues on Linux/Unix systems if called directly, as the shebang terminates with `\r`. Also did somt improvements to please flake8 ;)

### CODE REVIEW

**Comment by encbladexp** [comment]
I think none of the failed tests has anything todo with my small change.

**Comment by ohinckel** [comment]
No, it has nothing to do with your change. It has something to do with changes from @msinn. It's just failing here too because your work is based on the broken version.

**Comment by encbladexp** [comment]
@ohinckel / @msinn just tell me when devel is fixed, and i will rebase my PR on it.

**Comment by ohinckel** [comment]
This is already [fixed](https://github.com/smarthomeNG/smarthome/commit/b6a79d831e45b2349c7815120103837e23e03c01).

**Comment by encbladexp** [comment]
Rebased ;)

**Comment by msinn** [comment]
@encbladexp What does your PR do? You delete 118 lines of code and substitute them with 121 new lines of code. I just don't want to compare line by line what you changed.

**Comment by encbladexp** [comment]
Windows uses CRLF as line termination, unix systems LF. If you run an LF terminated Python file on Windows all is fine, but an CRLF on Linux raises an error as `\r` is part of the shebang. I created individual commit, so you can see the CRLF/LF and other changes independent.

Here is an example:
```
[stefan:~/…] staging(+68/-28)+* 126 ± cat /tmp/bla.py 
#!/usr/bin/python
print("Bla")
[stefan:~/…] staging(+68/-28)+* ± file /tmp/bla.py 
/tmp/bla.py: Python script, ASCII text executable, with CRLF line terminators
[stefan:~/…] staging(+68/-28)+* ± /tmp/bla.py
bash: /tmp/bla.py: /usr/bin/python^M: bad interpreter: No such file or directory
[stefan:~/…] staging(+68/-28)+* 126 ± file /tmp/bla.py 
/tmp/bla.py: Python script, ASCII text executable
[stefan:~/…] staging(+68/-28)+* ± /tmp/bla.py
Bla
```

**Comment by msinn** [comment]
What operating do you use? I have no problem on my Linux systems and have heared no complaints before.

**Comment by encbladexp** [comment]
Debian, Arch, Ubuntu… choose one ;)

```
[stefan:~/…] develop* ± file tools/conf_to_yaml_converter.py 
tools/conf_to_yaml_converter.py: Python script, ASCII text executable, with CRLF line terminators
[stefan:~/…] develop* ± tools/conf_to_yaml_converter.py 
/usr/bin/env: ‘python3\r’: No such file or directory
```

If you call the script with `python filename` all works fine, but not with the existing shebang. Nevermind, files for Depoyment on Linux/Unix Systems should **always** be LF terminated only.

**Comment by msinn** [comment]
You didn't answer my question

**Comment by msinn** [comment]
On Debian I dont get any errors

**Comment by encbladexp** [comment]
I posted the error message above, from a default Arch Linux Installation. Debian/Ubuntu has the same issues on a clean install. For reference `bin/smarthome.py` has LF line terminators and works fine on these systems.

**Comment by msinn** [comment]
You still didn't answer my question. Your PR deletes 118 lines but adds 121 lines. What did you change?

**Comment by encbladexp** [comment]
Just take a look at the **individual** commits of this PR. 1b74bf63df8a188b51d2bd4a3c1db60d09d47076 convertes from CRLF to LF, and a5cd55cff605e9ae10dc1a98d727fc991dd8c2c7 improved some flake8 related Issues.

**Comment by ohinckel** [comment]
> Your PR deletes 118 lines but adds 121 lines.

There was nothing changed: only one (empty) line was added in the code two lines (text was broke down into several lines) in the documenting comment. The line endings changed which makes the diff that large.

I prefer to only use LF in all files, but I don't have problems when someone is using CRLF. It only matters for developers and developers should be able to work with LF or CRLF.

But we should not use CRLF on the start of the file in the shebang to avoid such problem with starting the scripts on Linux systems. So why not using LF everywhere.

**Pull request merged**
