### PR TITLE
systemair: fix bug with unsigned temperatures

### PR DESCRIPTION
**Pull request by 4d4mu**
Hi,
My vent told me, that last night temperature was over +6500*C!
There's a bug in systemair plugin - all values are parsed as unsigned. Minimalmodbus has optional argument for signed/unsigned, but only for reading one reg, not group. Since group read is faster, i decided to convert temperatures with ctypes. According to systemair modbus manual, only heater regs contain temperatures and rest of heater regs doesn't exceed value 32767, so I applied fix to all heater regs (for simplicity).

### CODE REVIEW

**Comment by 4d4mu** [comment]
I was also thinking about storing set of temperature registers and conditionally casting only those regs to signed, with division /10 - instead of using item eval

**Comment by psilo909** [comment]
has to be retested by someone who uses this plugin before i can merge.

**Comment by 4d4mu** [comment]
Of course. @pfischi ?

**Comment by pfischi** [comment]
I will test it today. Thanks for bugfixing.

**Comment by 4d4mu** [comment]
No problem, what do you think about idea from second comment?

**Comment by pfischi** [comment]
Should be a good idea. This Wohle make the item.conf much cleaner. But i'am not sure that all registers are the same for all systemair devices. How we can detect in a smooth way whether the item/register is a temp value?

**Comment by 4d4mu** [comment]
systemair modbus documentation seems to be universal for many devices - in "7.6 Registers for system parameters" section we have list of 15 supported models. I can't find any other modbus documentation, so maybe we can assume that this one covers all (or most) devices. Basing on that, all temperature registers are in "7.2 Registers for heater control" section in address range 209-218. Scalling by 10 is also marked for this range.

**Comment by pfischi** [comment]
I've tested your patched code. Working fine. Can you please update your pull request by removing all eval statements from examples in 'Readme.md'. Thank you. After that the code can be comitted.

**Comment by 4d4mu** [comment]
done, updated also systemair.conf

**Comment by ohinckel** [comment]
What about
* making this plugin a `SmartPlugin`
* adding the required Python packages to a `requirements/plugin.systemair.txt` file

Do you think this can also be a part of this PR?

**Comment by psilo909** [comment]
@ohinckel is right, should not take too much time and i also told that others, who contributed a plugin. so we get a more homogenic plugin structure

**Comment by 4d4mu** [comment]
Where can I get more info about SmartPlugin?

**Comment by psilo909** [comment]
https://github.com/smarthomeNG/smarthome/wiki/SmartPlugin

**Comment by 4d4mu** [comment]
Implemented new idea last night, today in the evening if everything will be ok I'll push it. So far so good - working well, structure of whole plugin is simplified, time spent in _read_modbus() strongly reduced

**Comment by pfischi** [comment]
Very nice. I will test the code today in the evening. Thanks for your work.

4d4mu <notifications@github.com> schrieb am Do. 17. Nov. 2016 um 09:46:

**Comment by 4d4mu** [comment]
Done, only used register ranges are read. With my configuration exec time of _read_modbus() is reduced from ~1.7s to ~0.8s (in debug mode). Also changed the way coil items are stored: set() instead of dict() should be slightly faster. Signed registers stored as range(), but can be easily replaced with any iterable and applied to any registers set.

**Comment by psilo909** [comment]
@pfischi not if u wanna use the multi instance capability

**Comment by pfischi** [comment]
Is this necessary here?

**Comment by psilo909** [comment]
@pfischi i dont know... thought there already was some multi instance thing in the plugin. but i am not sure and did not check. if you say no i can accept the PR after the changes.. please also update the requirements file as @ohinckel wrote

**Comment by pfischi** [comment]
The plugin was not designed to be multi instanceable. So this should be fine. I'am currently testing the plugin. Tomorrow i'll give you feedback.

**Comment by ohinckel** [comment]
Even if this is not a multi-instance plugin, it should still use the `has_iattr` and `get_iattr_value` methods instead accessin `item.conf` directly. Just to use a generic interface to access the item configuration.

**Comment by 4d4mu** [comment]
ok, I'll try to make this plugin smart

**Comment by psilo909** [comment]
now a plugin specific requirements file in https://github.com/smarthomeNG/smarthome/tree/develop/requirements and we are fine ;)

**Comment by psilo909** [comment]
wait: i also miss the self.logger clause in the plugin

**Comment by 4d4mu** [comment]
`requirements/plugins.systemair.txt 
minimalmodbus>=0.7
pyserial>=3.0.1
`
is that good?

Ok, fixing logger

**Comment by psilo909** [comment]
i would say that should do it! thanks

**Comment by 4d4mu** [comment]
That's no problem. I'm using smarthome for some time - since v1.0 and just recently I discovered that someone is continuing this good work. I am glad that I can contribute :)

**Comment by psilo909** [comment]
@4d4mu we are glad, you do ;)

**Comment by pfischi** [comment]
@4d4mu thx for your contribution.

**Comment by ohinckel** [comment]
@4d4mu thanks updating the implementation and supporting us!

**Pull request merged**
