### PR TITLE
Change log level via CLI

### PR DESCRIPTION
**Pull request by ohinckel**
Sometimes it would be useful to change the log level on-the-fly to get debug log of a running instance without having to restart the complete system.

With this you can to this by using the CLI `log` command:

```
> log
RootLogger - INFO:
TimedRotatingFileHandler - NOTSET
> log debug
> log
RootLogger - DEBUG:
TimedRotatingFileHandler - DEBUG
> log info
> log
RootLogger - INFO:
TimedRotatingFileHandler - INFO
> 
```

Two new commands introduced:
- `log` - shows the current log
- `log level` - sets the log level to given value (e.g. info, debug)

### CODE REVIEW

**Comment by psilo909** [comment]
wouldnt it be better to change specific loglevels and not only the RootLogger? will this interfere with the new logging implementation of @cstrassburg ?

**Comment by ohinckel** [comment]
It will change the log level of all log handlers configured. So not it should not be a problem with the new log stuff introduced by @cstrassburg. The only thing which could be a problem would be that one has configured different handlers with different log levels. Using this command will set the log level of **all** handlers and you will not be able to set it back to different log levels for specific handlers (only restart will reconfigure the logger).

Possible solution could be
a) use command `log defaults` to reload the log configuration and reconfigure the logger or
b) extend thecommand to be able to specify the handler to set, e.g. `log <handler> debug`.

**Comment by psilo909** [comment]
@ohinckel thats what i mean.. all are set to the same level.. i would like to switch a specific handler if i would use that feature

**Comment by psilo909** [comment]
it would be also nice for backend plugin zu switch each log handler differently

**Comment by psilo909** [comment]
for me b) would be a good thing. for all you could do a "log all debug"?

**Comment by msinn** [comment]
I had the idea of building a backend function to confifure logging.
I like to read the logging.yaml and to have. Dialog to change loggers and handlers.
But it has to wait until mid of october.
I think it would be have a subset of that new feature set i cli as well.

**Comment by onkelandy** [comment]
would make debugging SO much easier ;)

**Comment by cstrassburg** [comment]
Falscher Ansatz meiner Meinung nach. Besser wäre es die logger aufzulisten und die vorhandenen dann modifizieren zu können. 
Dieser PR ist so kontraproduktiv zu dem implementieren Verfahren.

**Comment by ohinckel** [comment]
> Besser wäre es die logger aufzulisten und die vorhandenen dann modifizieren zu können.

War das nicht der Vorschlag aus dem letzten Komentar von mir? Die Angabe eines Loggers und deren Level.

> Dieser PR ist so kontraproduktiv zu dem implementieren Verfahren.

Welches "dem implementieren Verfahren" meinst du?

**Comment by cstrassburg** [comment]
Irgendwie verwendest du PRs als Backlog oder wie einen Entwicklungbranch. 
Ich kann nur die Änderungen in den Commits beurteilen und die kann ich so nicht commiten. 

Das implementierte und angestrebte Verfahren ist mehrere Logger zu verwenden und nichts mehr über den Root Logger laufen zu lassen.

**Pull request closed without merging**
