### PR TITLE
websocket: Ordered shutdown

### PR DESCRIPTION
**Pull request by mptei**
Referencing https://github.com/smarthomeNG/smarthome/pull/406#issuecomment-808949518.

The error messages are caused by the call of loop.stop() which was formerly commented out. So before the loop was simply not stopped and these errors couldn't occur.

This commit now tries to fix that (I don't had this error on my installation). 

The intention is:
* Stop the websocket to reject new connections
* Cancel the update tasks (they have use a `while True` loop; better would be perhaps a `while self.is_alive` or so)
* Cancel the server tasks
* Do the rest what was done before

This sequence works on my side. Also the seldom error what I had (`Task was destroyed but it is pending!`) didn't occured anymore.

### CODE REVIEW

**Comment by mptei** [comment]
Even a simpler shutdown.

**Comment by mptei** [comment]
Now, the websocket servers are closed and awaited. The rest is cancelled then.
This is fast and reliable so far.

**Comment by msinn** [comment]
Finally I got time to something for SmarthomeNG.

I installed your PR and ran into problems. In my Installation (Python 3.8) Websocket doesn't function amy more after installing the PR (neither smartVISU, nor the graphs in the admin interface). Reverting to the version without PR made websocket function again.

I have no warnings or errors in the log files, so I am stuck here, so I have to poke through the fog.
Which Python version are you using?

**Comment by bmxp** [comment]
@mptei do you have some more insight on questions by @msinn or can we close this PR?

**Comment by mptei** [comment]
Sorry, I gave up on SmarthomeNG.

**Pull request closed without merging**
