### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by CaeruleusAqua**
Adds a rate_limit Property for items, which allows to limit the number of changes of the item value within a period of time.
The rate_limit property should contain a time in seconds. If a new value is set within this time span, a timer is started instead, which sets the value only after the given time span has expired. This ensures that the last set value is always applied.

### CODE REVIEW

**Comment by msinn** [comment]
Could you elaborate to the use case(s) for this new item attribute?

**Comment by CaeruleusAqua** [comment]
E.g. An item what lands on the KNX bus and is frequently changed by other plugins / logics. I wanted to include this directly in the KNX plugin, but thought so it can be used for all plugins. For me, for example, the brightness value of a lamp which has spammed during dimming with almost 100Hz on the KNX bus.

**Comment by Morg42** [comment]
How do you propose to handle the mentioned 100 msg/sec, which one - if any - should be preserved, which should be rejected, and how many might "come through", if we assume 100 msg/sec for 1 sec as an example?

**Comment by Morg42** [comment]
Honestly, I don't really see a use case for this, so I'll keep back in discussion.

Two remarks:
1. the rate_limit attribute is already defined as "numeric", so an explicit cast should not be necessary
2. the description of the rate_limit attribute isn't clear - is rate_limit the max rate (number of msg/sec) or the minimum time between two messages? This should be clarified in any case

**Comment by Morg42** [comment]
No activity or answers for 2 months, possibly negative side effects (suppressing potentially important messages),  

vote for closing @msinn

**Comment by Morg42** [comment]
After another internal discussion this PR will not be merged.

**Pull request closed without merging**
