### PR TITLE
Season

### PR DESCRIPTION
**Pull request by Ageman**
Calculate the season of year into env.location.season 
0 Spring / 1 Summer / 2 Fall / 3 Winter

### CODE REVIEW

**Comment by psilo909** [comment]
i like that.. what do the others think?

**Comment by msinn** [comment]
I like the idea, but I don't understand the choice of the dates for the change of the seasons.

**Comment by Ageman** [comment]
I copied the snippet from here, they have some more background in the comment:
http://stackoverflow.com/questions/16139306/determine-season-given-timestamp-in-python-using-datetime

**Comment by Ageman** [comment]
oh, and hang on, I missed the comment about the wrong hemisphere calc. Let me correct that first.

**Comment by ohinckel** [comment]
Btw. wrong target branch, should be develop. Create new PR against develop branch.

**Comment by Ageman** [comment]
oops

**Comment by ohinckel** [comment]
Thanks for creating new PR #176.

**Pull request closed without merging**
