### PR TITLE
sample_plugin_webif

### PR DESCRIPTION
**Pull request by ThomasCr**
- I fixed a bug on register webif app
- some whitespace cleanups

### CODE REVIEW

**Comment by ThomasCr** [comment]
what's wrong with Travis?

**Comment by psilo909** [comment]
why are u modifying the sample plugin?

**Comment by msinn** [comment]
I don't see a reason for the change of the sample plugin.

**Comment by ohinckel** [comment]
I see a reason to change the sample plugin and I guess you saw it [recently](https://github.com/smarthomeNG/smarthome/commit/65dcc2e54fcc3297a0fa1c8d862198a4d92ef9b1), too.

One thing missing: the `TemplateNotFound` import. But do we really need this import @ThomasCr?

**Comment by ThomasCr** [comment]
without the TemplateNotFound import I got no information about the TemplateNotFound error.
So for good error reporting (maybe somebody deleted a template or made his own modifications) it should be included?

**Comment by ohinckel** [comment]
Really sure that you need to import this exception to get some better error reporting? I can't believe that the import will help here.

Can you recheck this? If it is not really required we could close this issue.

**Comment by ohinckel** [comment]
> without the TemplateNotFound import I got no information about the TemplateNotFound error.

Hmm, sounds strange to me because this way the outer code needs to know which exceptions occurs in the inner code to be able to handle them. I can't believe this or I didn't understand the problem correctly.

Btw. can you resolve the conflict?

**Comment by ohinckel** [comment]
I'll close this now. Conflicts still not resolved and PR contains only whitespace fixes - beside of this template exception thing, which could be not really necessary.

If somebody think different, please reopen.

**Pull request closed without merging**
