### PR TITLE
Enable MQTT-TLS + Follow-up to #474

### PR DESCRIPTION
**Pull request by laraveluser**
The TLS functions already marked are commented out. ca_certs must be a file that contains all certificates of the broker's certificate chain. 
If the system is only addressed internally and is encrypted via an external Let's Encrypt certificate, tls_set_insecure must be set because otherwise the IP validation will fail. In this case, ca_certs does not have to be set either.

Regarding https://github.com/smarthomeNG/smarthome/issues/474, the adjustment is still missing in the stop method.

### CODE REVIEW

**Comment by onkelandy** [comment]
This needs to be cleaned up. Only commit newly added things please

**Comment by Morg42** [comment]
The commit history is confusing; the actual diff is quite simple. 

As far as I can see, it only adds the tls parameters to mqtt module to enable TLS support already implemented in paho_client. I can't see any harmful effects.

Is this topic still current? Has someone tested this?

**Comment by Morg42** [comment]
Will be revisited when MQTT v5 protocol is being implemented

**Comment by laraveluser** [comment]
I have hardly any experience with pull requests so far. I was irritated myself that the system not only committed my changes but also others. I only use the web interface and I don't see any way to restrict the whole thing, otherwise I would delete the pull request and create a new one limited to my changes.

As a result, my pull request does not change much. It only concretises the already existing, but commented out implementation. The whole thing works, but only on a local level without a certificate check.

For me, the topic remains topical, as I would like to keep the adaptation effort after updates low and I may not be the only one who manually adapts the plugin after each update.

**Comment by onkelandy** [comment]
This is how to proceed:
copy all changed files to a save place.
clone your fork using sourcetree
Go to repository settings and add a remote: https://github.com/smarthomeNG/smarthome
Pull the develop branch from the newly added remote, push to your own fork.

After that create a new branch, copy the edited files into that and commit.
The newly created PR should now be clean.

**Pull request closed without merging**
