### PR TITLE
Update item.py to cast bool from bytes

### PR DESCRIPTION
**Pull request by hendrikmh**
Add ability to bool cast function to set value from bytes.
This is needed to allow plugins like MQTT to set bool item values.

### CODE REVIEW

**Comment by msinn** [comment]
Strings are casted to bool. Why should byte arrays be casted? What is the use case?

A generell remark: You should make pull requests against the develop branch, not against the master.

**Comment by hendrikmh** [comment]
Some plugins like the MQTT plugin get their strings as bytes in Python3 (i.e. a bool value from e.g. homebridge-mqtt is sent via MQTT in "text" form to the MQTT subscriber in smarthomeNG). When the MQTT plugin tries to assign the new values to items smarthomeNG raises a type error (b'true' not of required type bool).
Adding the required cast to the already existing casts from sting to bool seems to be the most logical solution the type casting would not need to be added to each and every plugin with the same "problem".

If the solution approach is OK I can provide a pull request against the develop branch.

**Comment by msinn** [comment]
If strings are handled as array of bytes, this usually comes from code that was originally written for Python 2.7 and converted to Python 3. The better way would be to correct this code instead of modifying the core of SmartHomeNG to handle it.

Which plugins beside the mqtt plugin have you found that handle strings as array of bytes?

While looking at the code in item.py to check your PR, I found an inconsistency in casting strings to bools in differnet parts of the core of SmartHomeNG. I am going to fix that in the next week or two.

**Comment by hendrikmh** [comment]
I have just seen this from MQTT plugin (actually did not search further plugins). Sounds like you prefer to have a conversion from bytes to strings in the MQTT plugin?

**Comment by msinn** [comment]
It wasn't only bool that was not casted, even casting to strings didn't work. The only casting that was working somehow was to num.

As a quick fix I updated the MQTT plugin to support type-casting. Dat data will be casted to the datatype you specify in items.conf / items.yaml.

With the modified MQTT plugin you should be able to do what you want.

Since the the MQTT plugin has a lot of shortcomings and design flaws, I am going to rewrite it from scratch.

If it is ok for you, I would close this pul request.

**Comment by hendrikmh** [comment]
Great thanks - was thinking the same way just no time yet. For the MQTT plugin I was thinking about another mode that would not register one topic per item but generic topics for get/set and from/to smarthomeNG requests that would send/receive more or less a  json representation of the item structure (maybe limited to some variables only). This would also simplify interactions with e.g. node-red or homebridge-mqtt.

PS: happy to get the pull request closed.

**Comment by msinn** [comment]
You don't need another mode for the MQTT plugin to receive json. Just set the datatype of your item to 'dict (which is a regular but seldom used SmartHomeNG datatype). You can also use the datatype 'list' to receive data as a list. At the moment this works only for receiving data, not for sending.

If you speak german, you can read about my plan to write a new mqtt plgin from scratch [here](https://knx-user-forum.de/forum/supportforen/smarthome-py/1083821-nutzt-von-euch-jemand-mqtt-mit-smarthomeng)

**Pull request closed without merging**
