### PR TITLE
Fix class name

### PR DESCRIPTION
**Pull request by robert-budde**
class_name should be written always the same - leads to confusion if it is sometimes spelled classname while meaning the same thing. Best example: https://knx-user-forum.de/forum/supportforen/smarthome-py/1422178-class_name-und-classname-konsolidierung-der-schreibweisen - this has to be merged together with the changes in the plugins (see https://github.com/smarthomeNG/plugins/pull/293)!

### CODE REVIEW

**Comment by msinn** [comment]
I Think this PR goes complete in the wrong direction. Two reasons:
- class_name in /etc/plugin.yaml is deprecated. Instead of class_name and class_path the parameter plugin_name should be used (and is used by the admin interface)
- This change would break SmartHomeNG for users that have private plugins, that are not part of the repository.

**Comment by psilo909** [comment]
I see at least one point there. even if we "kick out" class_path parameter, we have lots of other parameters named with "_". so a convention here would make at some kind of sense?!

for the time being we could at least keep both variants to ensure compatibility

**Comment by msinn** [comment]
...and we could keep both variants to ensure compatibility without having to change 213 files in two PR2

**Comment by msinn** [comment]
By now, in addition to the earlier comments there are a couple of conflicts, so I close the PR.

Conflicting files:
lib/module.py
lib/plugin.py
modules/admin/webif/static/assets/testdata/api/config/default.json
modules/mqtt/module.yaml
requirements/all.txt
requirements/base.txt

**Pull request closed without merging**
