### PR TITLE
abs2rel(self,t,ah) added

### PR DESCRIPTION
**Pull request by henfri**
returns relative humidity if the absolute humidity and the temperature are given

### CODE REVIEW

**Comment by msinn** [comment]
The PR contains a syntax error. Thats why the Travis CI build has failed. Please correct it.

When I asked for documentation, I was thinking about the usual Python style documentation, which is picked up when building the documentation.

An example from lib.plugin:
```
    def _get_conf_args(self, plg_conf):
        """
        Return the parameters/values for the actual plugin as args-dict
        
        :param plg_conf: loaded section of the plugin.yaml for the actual plugin
        :type plg_conf: dict
        
        :return: args = specified parameters and their values
        :rtype: dict
        """
```

**Comment by henfri** [comment]
I hope the documentation is ok now.

Greetings,
Hendrik

**Comment by msinn** [comment]
Perfect

**Comment by msinn** [comment]
Perfect

**Comment by msinn** [comment]
I think my merge is caught in the backlog caused by the github outage

**Pull request merged**
