### PR TITLE
backend: polish translation & small fixes

### PR DESCRIPTION
**Pull request by 4d4mu**
- added polish translation
- added missing "Löschen" to all translations (please check if correct, especially in fr)
- fixed hashed password generator - earlier I got error:
```
File "...smarthome/plugins/backend/utils.py", line 116, in create_hash
    return hashfunc.digest().hex()
AttributeError: 'bytes' object has no attribute 'hex'
```

### CODE REVIEW

**Comment by psilo909** [comment]
Kann das mit den hashed pwd gen jemand erklären? bei mir ist der fehler nicht (py 3.5)

**Comment by psilo909** [comment]
Unabh. davon: danke für die Übersetzung. Würdest Du die bis zum Release in Intervallen auch nachziehen?

**Comment by psilo909** [comment]
unabh. von der Klärung merge ich schon mal

**Comment by 4d4mu** [comment]
hash problem occurred in python 3.4.2 (Debian Jessie armv5tel). On other computer with python 3.5.2 it works well.
I have doubts about the need for translation of language names on the list and "Switch to language" phrase. I think that every position should be only in its own language only. For example: if you don't know what "Switch to English" or "Przełącz na polski" means, you probably shouldn't click it. Right now, when I want to add new language, I have to translate its name to all other languages. IMHO languages should be independent. One day, when SmartHomeNG will be world best and most popular open-source software for intelligent home with 50 translations, poor developer who wants to add 51th language shouldn't have to care about other 50.
If You agree with me, I could change it to make languages independent.

BTW I would really appreciate answers in English, I know only few words in German :)

**Comment by psilo909** [comment]
sorry, no problem. didnt know about that. i agree with you concerning language names. what do @bmxp and @Foxi352 think?

**Comment by bmxp** [comment]
I have no experience with several languages in software environments, so don't ask me ;-) What exactly would you like to change?

**Comment by 4d4mu** [comment]
I'd like to remove `"Auf Deutsch wechseln": "Switch to German",`  and `"Deutsch": "Deutsch",` and so on from all language files, then make proper translations straight in `plugins/backend/templates/services.html`, so language files will be independent

**Comment by msinn** [comment]
The implementation of translations in the backend plugin was a quick and dirty solution. While writing the backend plugin we discussed, that a translation mechanism for the whole SmartHomeNG environment should be implemented, so every plugin and logic can use the translation engine.

Back then we decided not to put too much effort into the backend-translation, since new languages don't get added every other day.

I think we should leave the backend-translation as it is and put the energy in a discussion how to implement a SmartHomeNG wide translation engine.

**Comment by psilo909** [comment]
@msinn i think he means that the "Auf Englisch wechseln" should be "Switch to English", even when German is selected... otherwise, if you dont know German, you dont know what to switch to.

**Comment by 4d4mu** [comment]
Exactly, but if it's temporary solution, I think we can leave it as it is

**Pull request merged**
