### PR TITLE
Implemented support for item configuration files in yaml - conflicts resolved

### PR DESCRIPTION
**Pull request by ohinckel**
As mentioned in https://github.com/smarthomeNG/smarthome/pull/107#issuecomment-246194057 I checkout the develop branch from @msinn and updated it with the latest `develop` version.

I got conflicts in:
* bin/smarthome.py - only different version value in `VERSION` constant
* lib/config.py - changes in `parse_conf()` vs. `parse()` API doc and `valid_*chars` variables
* lib/plugin.py - import statement added (one for `inspect` module, another for `os.path`)

Hopefully I merged it correctly. @msinn, it would be nice if you could review the complete patch (especially the parts with conflics) of this PR and give your OK.

### CODE REVIEW

**Comment by ohinckel** [comment]
@walldi, can you please have a look at this error (is only a problem with Python 3.2):

> test_backend_blocklylogics.py:9: in <module>
> from  tests.backend.cptestcase import BaseCherryPyTestCase
> E   ImportError: No module named backend.cptestcase

The builds are still failing because of this error which makes it complicated to find out which commit introduced a problem and which doesn't (you have too lookup the details in the build log).

**Comment by walldi** [comment]
I habe no idea yet. I do not with py3.2 myself.
Is there a way to disable single/all tests for this platform?

**Comment by ohinckel** [comment]
> I habe no idea yet. I do not with py3.2 myself.

I fixed it (see commits in `develop` branch https://github.com/smarthomeNG/smarthome/commit/c6c55e0f8b171cf5d7603e895516e65dfd99ea18 & https://github.com/smarthomeNG/smarthome/commit/3094af3f573160868c2b4712f9ba06aebf59c29a). So everything is green again :smiley: 

> Is there a way to disable single/all tests for this platform?

I think this is nothing we can just disable or enable. We still want to support this platform, so tests should be working on this platform too.

**Comment by ohinckel** [comment]
Can we merge this PR now or are there any objections?

**Comment by bmxp** [comment]
I think we can merge. Can you resolve the conflict above?

**Comment by ohinckel** [comment]
The conflicts were introduced with the last merge (PR #132). I'll try to fix the tests, but I'm no happy having duplicated tests just for different formats. Maybe I can extract the common parts and make it usable for all config formats (maybe other formats will be introduced in the future).

**Comment by ohinckel** [comment]
I refactored the config tests to base on same test implementation for different formats (conf, yaml). 

This requires to implement the recently added checks for digits in keys or reserved keywords in keys (see #63 & #132), too, which was added also. The implementation just removes the invalid keys from the dictionary (in a second step, like the comment removal stuff before - which was also refactored a little but for this).

Additionally it also adds new checks for items/keys with invalid chars. According to the tests, nothing should break :smiley:

**Comment by ohinckel** [comment]
@msinn, since this is now merged we should update the documentation for the new format.

**Pull request merged**
