### PR TITLE
Support for relative item references

### PR DESCRIPTION
**Pull request by msinn**
This PR implements relative item references.

See issue https://github.com/smarthomeNG/smarthome/issues/75

The (german) documentation for the feature can be found at https://github.com/smarthomeNG/smarthome/wiki/Items:-Relative-Item-Referenzen

### CODE REVIEW

**Comment by ohinckel** [comment]
Both new methods seems to be very complex and I think tests for these methods would be really nice.

**Comment by msinn** [comment]
There were no unit tests for item.py.

I wrote tests only for the new functionality of relative items addressing.

**Comment by ohinckel** [comment]
Thank you for testing this stuff. And of course it's OK to test only the new functionality you added.

Maybe we can move the `MockSmartHome` and `MockScheduler` to a common place to be able to use it in other tests too. And do we need all these `print()` statements there?

**Comment by psilo909** [comment]
i would merge this PR, but i also wonder about the "print()" ?

**Comment by msinn** [comment]
ohinkel ist talking about 12 print startements.

Unittest routes all logging to the console. To give all that output a bit structure, I added 8 print statements, so you can see more easily which of the 3 methods is beeing tested by the 21 tests iI am doing.

4 more print statements are from MockSmartHome(), which I copied from test_plugin.py.

The print statements to absolutely no harm and add only up to 12 lines of console output to all the lines that are produced by Unittest while running the 21 tests.

**Pull request merged**
